//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudiSoftWCF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Note
    {
        public Note(int v1, string v2, int v3, int v4, string v5)
        {
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public int idProfesor { get; set; }
        public int idEstudiante { get; set; }
        public string Valor { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
